version: '3.8'

networks:
  app-network:
    external: true

services:
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=bennrabbit
      - RABBITMQ_DEFAULT_PASS=Edidiong56
    networks:
      - app-network
